import { jsPDF } from 'jspdf'

export const generateMedicalReportPDF = (reportData) => {
  const doc = new jsPDF()
  
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const contentWidth = pageWidth - (margin * 2)
  let yPos = 20

  // Header
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('RADIOLOGY REPORT', pageWidth / 2, yPos, { align: 'center' })
  yPos += 15

  // Patient Information
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('PATIENT INFORMATION', margin, yPos)
  yPos += 8
  
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(`Patient: ${reportData.patientName} | ID: ${reportData.patientId}`, margin, yPos)
  yPos += 6
  doc.text(`Age: ${reportData.age} | Gender: ${reportData.gender}`, margin, yPos)
  yPos += 6
  doc.text(`Date: ${reportData.date}`, margin, yPos)
  yPos += 6
  doc.text(`Study: ${reportData.study}`, margin, yPos)
  yPos += 12

  // Clinical Indication
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('CLINICAL INDICATION', margin, yPos)
  yPos += 8
  
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  const indicationLines = doc.splitTextToSize(reportData.clinicalIndication, contentWidth)
  doc.text(indicationLines, margin, yPos)
  yPos += (indicationLines.length * 6) + 8

  // Findings
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('FINDINGS', margin, yPos)
  yPos += 8
  
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  reportData.findings.forEach(finding => {
    const findingLines = doc.splitTextToSize(`• ${finding}`, contentWidth - 5)
    if (yPos + (findingLines.length * 6) > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage()
      yPos = 20
    }
    doc.text(findingLines, margin + 5, yPos)
    yPos += (findingLines.length * 6) + 2
  })
  yPos += 6

  // Impression
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('IMPRESSION', margin, yPos)
  yPos += 8
  
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  reportData.impression.forEach((item, index) => {
    const impressionLines = doc.splitTextToSize(`${index + 1}. ${item}`, contentWidth - 5)
    if (yPos + (impressionLines.length * 6) > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage()
      yPos = 20
    }
    doc.text(impressionLines, margin + 5, yPos)
    yPos += (impressionLines.length * 6) + 2
  })
  yPos += 6

  // Recommendations
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('RECOMMENDATIONS', margin, yPos)
  yPos += 8
  
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  reportData.recommendations.forEach(rec => {
    const recLines = doc.splitTextToSize(`• ${rec}`, contentWidth - 5)
    if (yPos + (recLines.length * 6) > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage()
      yPos = 20
    }
    doc.text(recLines, margin + 5, yPos)
    yPos += (recLines.length * 6) + 2
  })
  yPos += 10

  // Validation Status
  if (yPos + 30 > doc.internal.pageSize.getHeight() - 20) {
    doc.addPage()
    yPos = 20
  }
  
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('VALIDATION STATUS', margin, yPos)
  yPos += 8
  
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(`Report Consistency: ${reportData.validation.consistency}`, margin, yPos)
  yPos += 6
  doc.text(`Confidence Score: ${reportData.validation.confidenceScore}`, margin, yPos)
  yPos += 6
  doc.text(`Template Compliance: ${reportData.validation.templateCompliance}`, margin, yPos)
  yPos += 10

  // Footer
  doc.setFontSize(8)
  doc.setFont('helvetica', 'italic')
  doc.text(`Generated by ${reportData.generatedBy} | ${reportData.processingTime}`, margin, yPos)
  
  // Add page numbers
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 30, doc.internal.pageSize.getHeight() - 10)
  }

  return doc
}

export const downloadPDF = (doc, filename) => {
  doc.save(filename)
}
